In [2]:
import numpy as np

In [3]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
a[..., 1]

array([1, 4, 7])

In [5]:
a = np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [6]:
a[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [7]:
a[1, ...]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [8]:
a[...] = 0
a

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
a = np.arange(27).reshape(3,3,3)

a[None].shape
# >>> (1, 3, 3, 3)
# 这里的`None`表示在指定位置(此处是第一维)添加一维。

a[:,None].shape
# >>> (3, 1, 3, 3)
# 这里的`None`表示在指定位置(此处是第二维)添加一维。

a[:,:,:,None].shape
# >>> (3, 3, 3, 1)
# 等价于
a[...,None].shape
# >>> (3, 3, 3, 1)

a[:,None,None].shape
# >>> (3, 1, 1, 3, 3)

In [13]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]

xyz = zip(x, y, z)
[print(x) for x in xyz]

(1, 4, 7)
(2, 5, 8)
(3, 6, 9)


[None, None, None]

In [14]:
x = [1, 2, 3]
y = [4, 5, 6, 7]
xy = zip(x, y)
[print(x) for x in xy]

(1, 4)
(2, 5)
(3, 6)


[None, None, None]

In [15]:
x = [1, 2, 3]
x = zip(x)
[print(a) for a in x]

(1,)
(2,)
(3,)


[None, None, None]

In [17]:
x = [1, 2, 3]

y = [4, 5, 6]

z = [7, 8, 9]

xyz = zip(x, y, z)
[print(x) for x in xyz]
u = zip(*xyz)

[print(x) for x in u]

(1, 4, 7)
(2, 5, 8)
(3, 6, 9)


[]

In [18]:
names = ['xiaoming', 'xiaohua', 'xiaohei', 'xiaoli']
jobs = ['coach', 'student', 'student', 'student', 'professor']

for name, job in zip(names, jobs):
  print(name, job)

xiaoming coach
xiaohua student
xiaohei student
xiaoli student


长度不够的元素会以None来填充，zip_longest提供了一个参数fillvalue，可以填充成我们指定的值。

In [19]:
from itertools import zip_longest
for name, job in zip_longest(names, jobs):
    print(name, job)

xiaoming coach
xiaohua student
xiaohei student
xiaoli student
None professor


zip除了方便我们迭代遍历之外，另一个很大的用处是可以很方便地生成dict。

我们调用zip返回的结果其实是一个迭代器，我们在转化成dict的时候自动遍历了迭代器当中的内容。比如我们如果直接打印出zip调用结果的话，就会发现屏幕上输出的是一个迭代器的地址：

In [22]:
names = ['xiaoming', 'xiaohua', 'xiaohei', 'xiaoli']
jobs = ['coach', 'student', 'student', 'student', 'professor']
hobbies = ['footbal', 'tennis', 'badminton', 'basketbal']

jobDict = dict(zip(names, jobs))
print(list(zip(names, jobs)))
print(jobDict)

[('xiaoming', 'coach'), ('xiaohua', 'student'), ('xiaohei', 'student'), ('xiaoli', 'student')]
{'xiaoming': 'coach', 'xiaohua': 'student', 'xiaohei': 'student', 'xiaoli': 'student'}
